type Query {
  bookById(id: ID!): Book
  authorById(id: ID!): Author
  getBooks(filter: BooksFilter): [Book!]!
}

type Book {
  id: ID!
  name: String
  pageCount: Int
  author: Author
}

type Author {
  id: ID!
  firstName: String
  lastName: String
  publishedBooks: [Book!]!
}

type Mutation {
  #author
  createAuthor(author: AuthorInput): Author
}

enum Genre {
  ACTION
  ADVENTURE
  COMEDY
  TERROR
  TECHNICAL
}

input BooksFilter {
  genres: [Genre],
  maxPages: Int
}

input AuthorInput {
  firstName: String!
  lastName: String!
}