spring.application.name=graphql
spring.graphql.graphiql.enabled=true

spring.jpa.hibernate.ddl-auto=create   
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://localhost:5432/book-shop
spring.datasource.username=postgres
spring.datasource.password=postgres@local

# Deixado dessa forma para testes
spring.jpa.hibernate.ddl-auto=create-drop